# pragma once
# include <ESP_Music.h>

/*
    I didnt know what song to use so I used jingle bells bruh
    generated by chatgpt
*/

const int bpm = 150;

Note melody[] = {
    {NOTE_E4, N8}, {NOTE_E4, N8}, {NOTE_E4, N4}, {NOTE_REST, N8},
    {NOTE_E4, N8}, {NOTE_E4, N8}, {NOTE_E4, N4}, {NOTE_REST, N8},

    {NOTE_E4, N8}, {NOTE_G4, N8}, {NOTE_C4, N8}, {NOTE_D4, N8},
    {NOTE_E4, N2}, {NOTE_REST, N8},

    {NOTE_F4, N8}, {NOTE_F4, N8}, {NOTE_F4, N8}, {NOTE_F4, N8},
    {NOTE_F4, N8}, {NOTE_E4, N8}, {NOTE_E4, N8}, {NOTE_E4, N16}, {NOTE_E4, N16},

    {NOTE_D4, N8}, {NOTE_D4, N8}, {NOTE_E4, N8}, {NOTE_D4, N8},
    {NOTE_G4, N2}, {NOTE_REST, N8},
};

const int melodyLength = sizeof(melody) / sizeof(Note);